### ISSUE TITLE
nginx flavour (non-nomad) has non-persistent configuration

### ISSUE THREAD

**Issue by Sidicer** [bsdpot/potluck#38]
Hello. I've noticed while trying to reference [potluck/nginx](https://github.com/bsdpot/potluck/tree/master/nginx) flavour that it would shut down after running `pot start -p nginx` and cook script finishes.

As there are other nginx flavours in potluck which are for `nomad` and the [README.md](https://github.com/bsdpot/potluck/blob/master/nginx/README.md) states `this jail is not for use with nomad` I think the [flavour cmd](https://github.com/bsdpot/potluck/blob/master/nginx/nginx) file needs to be updated to enable persistence:

```diff
-- set-attribute -A persistent -V OFF
-- set-attribute -A no-rc-script -V ON
++ set-attribute -A persistent -V ON
```

**Comment by bretton** [comment]
Hi @Sidicer thanks, I'll update shortly and remove the flags entirely. That's a legacy image which hasn't updated to the new format yet.

**Comment by Sidicer** [comment]
Thank you @bretton for checking the flavour and updating it, but I have still faced the original issue where the Pot/Jail is shut down right after starting it, even with `runs_in_nomad="false"`.
To stay persistent it requires `set-attribute -A persistent -V ON` in pot cmd file.

Have I misinterpreted this flavours` purpose and it is not meant to be ran persistently ?

```sh
cd potluck && git pull
cd potman && cp -r ../potluck/nginx flavours/.
```

```sh
potman build -v -d ../flavours freebsd
# 11. Build pot image
# /var/cache/pot/13.2-RELEASE_base.txz - 190 MB 5682 kBps - 34s
# 17. Success
potman publish -v -d ../flavours freebsd
potman catalog
# freebsd_13_2_1.3
```

```sh
potman build -v nginx
potman publish -v nginx
potman catalog
# freebsd_13_2_1.3
# nginx_13_2_1.0.10
```

```sh
sudo pot import -p nginx -t 13_2_1.0.10 -U http://10.100.1.1:10180
# ===>  importing nginx @ 13_2_1.0.10 as nginx_13_2_1_0_10
# ===>  Pot nginx_13_2_1_0_10 depends on freebsd_13_2_1_3 (@1706528407)
# ===>  Installing dependency freebsd_13_2_1_3
# ===>  importing freebsd_13_2 @ 1.3 as freebsd_13_2_1_3

sudo pot list
# pot name : nginx_13_2_1_0_10
#       network : public-bridge
#       ip : 10.192.0.5
#       active : false
```

```sh
sudo pot start -p nginx_13_2_1_0_10
# ===>  Starting the pot nginx_13_2_1_0_10
# Starting nginx.
# Mon Jan 29 11:53:42 UTC 2024
# p465b791c14a9b:

sudo pot list 
# pot name : nginx_13_2_1_0_10
#        network : public-bridge
#        ip : 10.192.0.5
#        active : false
```

**Comment by grembo** [comment]
@bretton @Sidicer Turns out the freebsd flavour that ships with potman turned off persistence. As it seems likely that users will use it as a base image (at least for testing purposes), I removed that configuration in https://github.com/bsdpot/potman/commit/96052e265c07a16ba01ba3e874fa702b195b2f9a (and bumped versions in https://github.com/bsdpot/potman/commit/5fff9fa248db7a6948a949617580c10ee67764b5).
