### ISSUE TITLE
Friendly reminder of repository name change

### ISSUE THREAD

**Issue by borestad** [bsdpot/potluck#55]
Hi!

Just a friendly reminder that the repository blocklist-ip was renamed to blocklist-abuseipdb a long time ago:

https://github.com/borestad/blocklist-abuseipdb

Source: https://github.com/bsdpot/potluck/blob/master/rbldnsd/README.md

Fortunately - github is kind enough to do a 301 redirect, but I'm not sure if there's a expiry date to how long they're making that 301.

All the best 😊

**Comment by bretton** [comment]
thanks @borestad , updating

**Comment by bretton** [comment]
This has been updated
